import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import SessionProviders from "@/providers/SessionProviders";
import { Toaster } from "react-hot-toast";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Chat App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <SessionProviders>
          {children}
          <Toaster/>
        </SessionProviders>
      </body>
    </html>
  );
}
